// Generate src/operations.generated.ts from the API's /openapi.json.
//
// The OpenAPI registry in the app is the single source of truth for every
// operation: name (operationId), method, path, agent-facing description,
// input schema, and x-mcp (title + tool annotations). The hosted /mcp
// endpoint reads it directly; this package ships a committed copy so a given
// release always exposes the same tools.
//
//   npm run generate                                        # from prod
//   ANIMALHOUSE_API_URL=http://localhost:3333/api npm run generate
//   npm run generate -- --check                             # fail if out of date

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "src", "operations.generated.ts");
const apiBase = process.env.ANIMALHOUSE_API_URL || "https://animalhouse.ai/api";
const specUrl = apiBase.replace(/\/api\/?$/, "") + "/openapi.json";
const check = process.argv.includes("--check");

const spec = await (await fetch(specUrl)).json();

const operations = [];
for (const [path, methods] of Object.entries(spec.paths)) {
  for (const [method, op] of Object.entries(methods)) {
    const meta = op["x-mcp"];
    if (!meta) throw new Error(`${op.operationId} has no x-mcp in ${specUrl}`);

    // One input object: path and query parameters, then the JSON body's fields.
    const properties = {};
    const required = [];
    for (const p of op.parameters ?? []) {
      properties[p.name] = { ...p.schema, ...(p.description ? { description: p.description } : {}) };
      if (p.required) required.push(p.name);
    }
    const body = op.requestBody?.content?.["application/json"]?.schema;
    for (const [name, prop] of Object.entries(body?.properties ?? {})) properties[name] = prop;
    for (const name of body?.required ?? []) if (!required.includes(name)) required.push(name);

    const upper = method.toUpperCase();
    operations.push({
      name: op.operationId,
      title: meta.title,
      method: upper,
      path,
      description: `Wraps ${upper} ${path}. ${op.description ?? ""}`.trim(),
      auth: Boolean(op.security?.length),
      annotations: meta.annotations,
      inputSchema: { type: "object", properties, ...(required.length ? { required } : {}) },
    });
  }
}

const text = `// GENERATED by scripts/generate.mjs from ${specUrl.replace(/^http:\/\/localhost:\d+/, "https://animalhouse.ai")}.
// Do not edit by hand: run \`npm run generate\` after the API changes.

import type { GeneratedOperation } from "./operation-types.js";

export const OPERATIONS: GeneratedOperation[] = ${JSON.stringify(operations, null, 2)};
`;

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== text) {
    console.error(`src/operations.generated.ts is out of date with ${specUrl}. Run: npm run generate`);
    process.exit(1);
  }
  console.log(`operations.generated.ts matches ${specUrl} (${operations.length} operations).`);
} else {
  writeFileSync(OUT, text);
  console.log(`Wrote src/operations.generated.ts: ${operations.length} operations from ${specUrl}.`);
}
